### ISSUE TITLE
请问我该怎么编译这个插件

### ISSUE THREAD

**Issue by pspupsp** [jiongjionger/NeverLag#30]
2.0版虽然没有完工，但1.3版在我的1.12的服务端已经无法正常运行，请问我编译这个2.0版要用到什么api呢，另外bukkit api我该用什么版本呢？求大佬解答

**Comment by andylizi** [comment]
这个插件的开发进度还没达到能够运行在生产环境的最低要求。

哦，通俗的说就是还不能用。

**Comment by pspupsp** [comment]
额，╮(╯-╰)╭好吧，谢谢

**Comment by pspupsp** [comment]
我试着在eclipse上运行了下。。。
Class not found cn.jiongjionger.neverlag.utils.VersionUtilsTest
java.lang.ClassNotFoundException: cn.jiongjionger.neverlag.utils.VersionUtilsTest
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:688)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:421)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Class not found cn.jiongjionger.neverlag.system.TpsWatcherTest
java.lang.ClassNotFoundException: cn.jiongjionger.neverlag.system.TpsWatcherTest
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:688)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:421)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by andylizi** [comment]
Bukkit 插件当然不能直接在 IDE 中运行。
如果想自己编译，可以安装 [Maven](https://maven.apache.org/download.cgi)（具体方法请百度），然后 clone 或[下载](https://github.com/jiongjionger/NeverLag/archive/master.zip)这个项目的代码，在根目录中执行 `mvn package` 命令，然后等待 Maven 下载完所有依赖。
如果一切顺利，你将在 `target` 文件夹中找到构建出来的 jar 文件。

**Comment by andylizi** [comment]
现在可以在 https://jitpack.io/com/github/jiongjionger/NeverLag/master-SNAPSHOT/NeverLag-master-SNAPSHOT.jar 直接下载到 `master` 分支的最新版本。
