### ISSUE TITLE
neverlag和史莱姆方块（匠魂）以及活塞混合产生的error

### ISSUE THREAD

**Issue by arnesacnussem** [jiongjionger/NeverLag#32]
```
[08:40:41] [Server thread/ERROR] [Minecraft/]: Could not pass event BlockPistonExtendEvent to NeverLag v1.3.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.block.BlockPistonBase.func_150078_e(BlockPistonBase.java:144) [app.class:?]
	at net.minecraft.block.BlockPistonBase.func_149695_a(BlockPistonBase.java:114) [app.class:?]
	at net.minecraft.world.World.func_147460_e(World.java:1099) [ahb.class:?]
	at net.minecraft.world.World.func_147459_d(World.java:1036) [ahb.class:?]
	at net.minecraft.block.BlockRedstoneWire.func_150177_e(BlockRedstoneWire.java:83) [ana.class:?]
	at net.minecraft.block.BlockRedstoneWire.func_149695_a(BlockRedstoneWire.java:330) [ana.class:?]
	at net.minecraft.world.World.func_147460_e(World.java:1099) [ahb.class:?]
	at net.minecraft.world.World.func_147441_b(World.java:1062) [ahb.class:?]
	at net.minecraft.block.BlockRedstoneDiode.func_149911_e(BlockRedstoneDiode.java:247) [akj.class:?]
	at net.minecraft.block.BlockRedstoneRepeater.func_149749_a(SourceFile:132) [anf.class:?]
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:655) [apx.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:812) [ahb.class:?]
	at net.minecraft.block.BlockRedstoneDiode.func_149674_a(BlockRedstoneDiode.java:73) [akj.class:?]
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:702) [mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:284) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchFieldError: SLIME_BLOCK
	at jiongjionger.listener.AntiPMM.onBlockPistonExtend(AntiPMM.java:25) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor257.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
	... 23 more
```

以上为报错，每次活塞动作都会发生该错误，有概率导致服务器卡死（玩家连接超时）

**Comment by jiongjionger** [comment]
Caused by: java.lang.NoSuchFieldError: SLIME_BLOCK
老版本的NeverLag在1.7的服务端关闭AntiPMM功能即可解决。
