### ISSUE TITLE
neverlag 1.3.0在Paper端出现 is it up to date问题

### ISSUE THREAD

**Issue by unknown10777** [jiongjionger/NeverLag#47]
Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
插件列表：banbadword, BanBadWords*, BKCommonLib, BungeeTabListPlus, ChairStairs*, ChestCommands, ColorMOTD*, Essentials, floodgate, GroupManager*, HolographicDisplays, ImageMaps, MiaoChat, Multiverse-Core, NeverLag*, PlaceholderAPI, ProtocolLib, ServerPingLib, ServerTeleport*, SuperVanish, Train_Carts, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldBorder
（均最新版本）
错误信息：

[17:51:49 ERROR]: Error occurred while enabling NeverLag v1.3.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'void com.comphenix.protocol.events.PacketAdapter.<init>(org.bukkit.plugin.Plugin, com.comphenix.protocol.events.ConnectionSide, com.comphenix.protocol.events.ListenerPriority, java.lang.Integer[])'
        at jiongjionger.NeverLag$1.<init>(NeverLag.java:358) ~[?:?]
        at jiongjionger.NeverLag.onEnable(NeverLag.java:359) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-243]        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:830) [?:?]

在另一个server Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)中，问题未出现。这两个文件（config。yml；neverlag1.3.0.jar 均相同）
插件列表：BanBadWords*, BungeeTabListPlus, ChairStairs*, ChestCommands, CoreProtect, Essentials, floodgate, GroupManager*, LockettePro, MiaoChat, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, NeverLag*, PlaceholderAPI, ProtocolLib*, Residence, ServerTeleport*, SuperVanish, UBBDispenserShulkerBoxFixer*, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldBorder
（均最新版本）

**Comment by shaokeyibb** [comment]
这不是 *is it up to date* 问题... 这是 *java.lang.NoSuchMethodError* 问题
因此，尝试将你的 ProtocolLib 降级以解决此问题

而且 NeverLag 多久没更新了你竟然在这里问问题，也是够稀奇的

**Comment by unknown10777** [comment]
> 这不是 _is it up to date_ 问题... 这是 _java.lang.NoSuchMethodError_ 问题
> 因此，尝试将你的 ProtocolLib 降级以解决此问题
> 
> 而且 NeverLag 多久没更新了你竟然在这里问问题，也是够稀奇的

我降级升级都试过了，最新的protocollib都能运行

**Comment by andylizi** [comment]
这个方法是 2020 年 6 月移除的：https://github.com/dmulloy2/ProtocolLib/commit/fdd30a7b87f25568f9a101ca12d99ab90d153d23#diff-66ad9e35c59562ae792cd6e943c96beecb620e35928d9b43dfd4d5d311647185

用 4.6.0 之前的版本就好了。最新的是 4.5.1。
